version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.apis:google-api-services-drive
    versions:
    - v3-rev20201130-1.31.0
    - v3-rev20210201-1.31.0
    - v3-rev20210207-1.31.0
    - v3-rev20210228-1.31.0
    - v3-rev20210315-1.31.0
  - dependency-name: com.google.api-client:google-api-client
    versions:
    - 1.31.2
    - 1.31.3
  - dependency-name: com.google.oauth-client:google-oauth-client-jetty
    versions:
    - 1.31.4
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
  - dependency-name: org.apache.tika:tika-parsers
    versions:
    - "1.22"
