#!/usr/bin/expect
spawn telnet localhost 10113
expect "username"
send "root\r"
expect "password"
send "root\r"
expect "command1"
send "create-table gramener.wordcount --t in-memory --flexible true"
send "\r"
expect "Table successfully created"
send "populate-table gramener.wordcount /tmp/ophadoop/wordCount/wordCount.txt-r-00000 false /tmp/ophadoop/wordCount/wordCountSchema.txt-r-00000"
send "\r"
expect "Table successfully populated"
expect "Table successfully populated"
send "create-table gramener.wordtweets --t in-memory --flexible true"
send "\r"
expect "Table successfully created"
send "populate-table gramener.wordtweets /tmp/ophadoop/wordTweets/wordTweets.txt-r-00000 false /tmp/ophadoop/wordTweets/wordTweetSchema.txt-r-00000"
send "\r"
expect "Table successfully populated"
expect "Table successfully populated"
send "create-table gramener.tagmapping --t in-memory --flexible true"
send "\r"
expect "Table successfully created"
send "populate-table gramener.tagmapping /tmp/ophadoop1/part-r-00000 false /tmp/ophadoop1/tagMapSchema.txt"
send "\r"
expect "Table successfully populated"
expect "Table successfully populated"

create-table test.Test1 --t in-memory --flexible true --df /tmp/iphadoop/ip1 --dft HadoopOutput --dfh true --dfs space --dfsl 0
populate-table test.Test1 /tmp/iphadoop/ip1 true null
